/cx/lslidar_driver_node:
  ros__parameters:
    packet_rate: 1695.0
    device_ip: 192.168.1.200 # LiDAR IP address
    msop_port: 2368 # LiDAR data port
    difop_port: 2369 # LiDAR device port
    pcl_type: false # Point cloud type true: xyzi
    add_multicast: false # Whether to use multicast mode true: use multicast
    group_ip: 224.1.1.2 # Multicast IP
    use_time_service: false # Whether to use external time service (GPS PTP NTP) true: use external time service
    min_range: 0.15 # Minimum scanning range (points below this value will be filtered)
    max_range: 10.0 # Maximum scanning range (points above this value will be filtered)
    angle_disable_min: 0 # Minimum angle crop for scanning (unit: 0.01°)
    angle_disable_max: 0 # Maximum angle crop for scanning (unit: 0.01°)
    distance_unit: 0.1
    horizontal_angle_resolution: 0.36 #10Hz:0.18  20Hz:0.36 5Hz: 0.09
    frame_id: lidar_link # Point cloud frame ID
    topic_name: lslidar_point_cloud # Point cloud topic name
    publish_scan: false # Whether to publish laserscan topic
    scan_num: 15 # Laserscan line number
    coordinate_opt: false # Point cloud 0 degree direction true: positive x-axis direction
    #pcap: /home/ls/Downloads/xxx.pcap   # pcap file path, uncomment when parsing pcap files offline
